### ISSUE TITLE
Popup Search跟Select like opera有冲突。

### ISSUE THREAD

**Issue by rcyggdra** [lkytal/GM#10]
Popup Search & Select like opera同时开启，翻译框位置异常，出现在网页左上角；
禁用Select like opera后， 翻译框位置正常。

**Comment by lkytal** [comment]
能否提供一些出现错误的网址?

**Comment by rcyggdra** [comment]
昨天是在任何网站都有错误，但是今天打开却没有问题了。
是浏览器问题呢，还是TM的问题呢。
win10-64bit+Chromium 64-64bit+Tampermonkey 4.5
