### ISSUE TITLE
能否让搜索页面在当下活动页面的右侧？

### ISSUE THREAD

**Issue by blob2015** [lkytal/GM#12]
当下，是跳到所有标签的最右（或者说最后面），对于习惯多开标签的家伙来说，有点点痛苦。
FF自带的搜索——拉去、右键单击——是跳到当下标签的右侧，有没有可能，也如此这般？
谢谢。

**Comment by lkytal** [comment]
目前, userscript脚本没有权限控制打开的位置, 也许以后我会移植扩展版本.

**Comment by blob2015** [comment]
:ok:
