### ISSUE TITLE
Text to link 那个脚本有个 bug

### ISSUE THREAD

**Issue by Kongzq** [lkytal/GM#13]
打开 https://www.zhihu.com/pin/973105969013731328 ，点击第一个 url ，打开的是https://github.com/wsdjeg/vim-g      ，  但其实他真正的 url  是 https://github.com/wsdjeg/vim-galore-zh_cn/blob/master/README.md

**Comment by lkytal** [comment]
在我这里测试没有问题, 请问你用的是什么版本的浏览器和脚本管理器?
