### ISSUE TITLE
Popup search translation

### ISSUE THREAD

**Issue by ledemon** [lkytal/GM#2]
The translation always translate all languages to chinese. Will be better if they can be translated to mi local language or choose one in the settings script.

Salutes, from Argentina.

**Comment by lkytal** [comment]
I would like to invite you to try the beta version below, please tell let me know whether this version works for you.

[https://github.com/lkytal/GM/raw/master/popsearch.user.js](https://github.com/lkytal/GM/raw/master/popsearch.user.js)

**Comment by ledemon** [comment]
Thanks, now translate all language to my local language, included my local language, if it is not very upset make the translation from local language maybe to english.

Examples:
english -> spanish (useful)
chinese -> spanish (useful)
spanish -> spanish (not useful)
spanish -> english (useful)
