### ISSUE TITLE
功能性bug: 选中文本视作链接打开 / Open selection as url错误

### ISSUE THREAD

**Issue by jsonlog** [lkytal/GM#39]
在chrome浏览器打开**某些**网站使用如下功能:
选中文本视作链接打开 / Open selection as url会丢失冒号
比如:在这个页面( http://www.cnplugins.com/tool/chrome-plugins.html )中
将chrome://flags 选中文本视作链接打开跳转成 https://chrome//flags
之前也遇到过几次类似的
http://xxxxx 变成http//xxxxx 然后跳转变成 https://http//xxxxx
关掉所有其它脚本也没用

**Comment by lkytal** [comment]
Fixed in 4.3.4
