### ISSUE TITLE
Popup Search的自定义能否实现一个id多个href?

### ISSUE THREAD

**Issue by sknnks** [lkytal/GM#41]
```
 [
    {
        id: "1",
        title: "Example Engine",
        description: "自定义引擎示例",
        src: "http://lkytal.website.com/ic.ico",
        href: "https://www.websiteAAA.com/search?q=${text}"
        href: "https://www.websiteBBB.com/search?q=${text}"
    }
] 
```
大致想表达的就是这样，选中文字后一次过打开多个网站来搜寻

**Comment by lkytal** [comment]
在版本5.2.0支持function功能, 可以实现这样效果, 如

{
			id: "UserEngine_function"
			title: "Example of User Engine use function"
			description: "function自定义引擎示例 / Example of user engine use function"
			src: "https://github.com/lkytal/GM/raw/master/icons/atom.png"
			function: "OpenUrl('https://aaa.com/q=' + text); OpenUrl('https://bbb.com/q=' + text);"
		}
