### ISSUE TITLE
Popup Search如何在动作之后让图标不消失？

### ISSUE THREAD

**Issue by CodesHunger** [lkytal/GM#47]
选择文本之后可能进行多个操作，如在不同的搜索引擎搜索，复制，翻译等，这样又需要多次选择。如果可以让它一直显示，直到点击页面其他地方再消失就好了。
请问怎样才能达到这样的效果呢？

另外相比其他类似脚本，这个使用起来更加方便，尤其是添加搜索引擎方面，感谢作者。

**Comment by lkytal** [comment]
在新版本中引入了"点击页面不隐藏"选项
