### ISSUE TITLE
脚本一直提示更新icon失败

### ISSUE THREAD

**Issue by megaslx** [lkytal/GM#54]
默认的几个icon一直提示更新失败

**Comment by chocoboplus** [comment]
`<a href="https://sm.ms/image/tpF7NjEiChdgcG4" target="_blank"><img src="https://i.loli.net/2021/02/07/tpF7NjEiChdgcG4.jpg" ></a>`
坏掉了！

**Comment by lkytal** [comment]
已经更新

**Comment by chocoboplus** [comment]
> 已经更新

蟹蟹！
