### ISSUE TITLE
5.0.2有个问题

### ISSUE THREAD

**Issue by xiaozixun** [lkytal/GM#57]
会造成依次同时打开多个页面，如图。
![录制](https://user-images.githubusercontent.com/22409452/110229950-0dc02080-7f48-11eb-84b4-cf201ef56db7.gif)

**Comment by lkytal** [comment]
Fixed in 5.0.3

**Comment by xiaozixun** [comment]
> 
> 
> Fixed in 5.0.3

这个问题修正了，可以关闭问题了。
