### ISSUE TITLE
在百度的页面中，Console 提示 TypeError: window.MutationObserver is not a constructor

### ISSUE THREAD

**Issue by ssrkaze** [lkytal/GM#61]
经查找，导致问题的可能是百度页面中引用的一个 all_async_search 开头的 js 文件，在该文件中可以找到如下代码：

```javascript
try{
    window.MutationObserver=window.WebKitMutationObserver=window.MozMutationObserver=null
}catch(e){}
```
该代码导致 **window.MutationObserver** 函数不可用，从而导致浏览器抛出异常:

> Uncaught (in promise) TypeError: window.MutationObserver is not a constructor

希望作者大大能加入相应的 Polyfill。

本人检测时，使用的是 Chrome 92.0.4515.107 版本，已经禁用其他插件及脚本。
Text To link 的版本为 2.8.7，来源 greasyfork，脚本管理器为 Tampermonkey。
在本人的页面中，导致问题的脚本连接为
https://ss1.bdstatic.com/5eN1bjq8AAUYm2zgoY3K/r/www/cache/static/protocol/https/global/js/all_async_search_9ada74a.js

**Comment by lkytal** [comment]
虽然有一些可以绕过的方法, 但是会在其他网页带来很大的副作用. 无奈我只能决定放弃处理baidu的烂摊子
