### ISSUE TITLE
Popup_Search翻译不能用了，提示Translate Error:

### ISSUE THREAD

**Issue by linranc** [lkytal/GM#63]
挺突然的
不翻墙提示`Translate Error:`
翻墙提示
```
Translate Error:
Bad Request
```

**Comment by guoh27** [comment]
+1

**Comment by wuilliam104286** [comment]
+1

**Comment by guoh27** [comment]
462行，工作账号就不提request了

```javascript
method: 'GET',
    url: `https://translate.google.cn/translate_a/single?client=gtx&dj=1&q=${popData.text}&sl=auto&tl=${lang}&hl=${lang}&ie=UTF-8&oe=UTF-8&source=icon&dt=t&dt=bd`,
    //data: `client=gtx&dj=1&q=${popData.text}&sl=auto&tl=${lang}&hl=${lang}&ie=UTF-8&oe=UTF-8&source=icon&dt=t&dt=bd`,
```

**Comment by lkytal** [comment]
Fixed

**Comment by linranc** [comment]
> 463行，改成这样，工作账号就不提request了
> 
> ```js
>     method: 'GET',
>     url: `https://translate.google.cn/translate_a/single?client=gtx&dj=1&q=${popData.text}&sl=auto&tl=${lang}&hl=${lang}&ie=UTF-8&oe=UTF-8&source=icon&dt=t&dt=bd`,
>     //data: `client=gtx&dj=1&q=${popData.text}&sl=auto&tl=${lang}&hl=${lang}&ie=UTF-8&oe=UTF-8&source=icon&dt=t&dt=bd`,
> ```

翻墙可以用，不翻墙还是不行
可能吧
