### ISSUE TITLE
5.1.0的翻译还是不能用，同时报告自动复制这个功能的一个bug。

### ISSUE THREAD

**Issue by xiaozixun** [lkytal/GM#64]
错误提示：
Translate Error:
Too Many Requests
我本以为是Firefox限制了，但edge也是无法翻译，只是奇怪的是：greasyfork.org/zh-CN/scripts/16203这个却能用。

自动复制的bug：每次复制之后都是会复制两次，一次是文字，一次是空白，如图所示，
![批注 2021-09-25 110345](https://user-images.githubusercontent.com/22409452/134755808-2d14b68d-bc24-4fb8-97be-f23f5127ccc5.png)

**Comment by ifwlzs** [comment]
可以看看这个，不知道能不能解决 #65

**Comment by lkytal** [comment]
这很奇怪, 因为我这里是正常的. 我又更新了一个版本, 请尝试并反馈. 同时修正了自动复制

**Comment by xiaozixun** [comment]
> 
> 
> 这很奇怪, 因为我这里是正常的. 我又更新了一个版本, 请尝试并反馈. 同时修正了自动复制

![批注 2021-09-28 105835](https://user-images.githubusercontent.com/22409452/135015552-e150c91b-98ce-4dd7-b72f-3c4369a55cd9.png)
![批注 2021-09-28 105944](https://user-images.githubusercontent.com/22409452/135015660-1b096816-7820-42c1-bf3c-9a1338c0e2e4.png)
![批注 2021-09-28 110441](https://user-images.githubusercontent.com/22409452/135016058-30833e57-2d5a-4d26-a174-ee2ebeb32e44.png)
自动复制似乎好了，翻译一直都不行。
