### ISSUE TITLE
Popup Search 在某些论坛里会造成网页前进后退失灵

### ISSUE THREAD

**Issue by LoneFireBlossom** [lkytal/GM#68]
诸如https://forum.hapigo.com https://community.nssurge.com 这种，我不知道怎么称呼？就这种框架开发的论坛得手动把popupsearch插件关掉。希望作者能相应处理一下

**Comment by lkytal** [comment]
在我这里没有出现这种情况, 请检查扩展冲突

**Comment by LoneFireBlossom** [comment]
试了试发现是使用ADGuard安装就会这样。
用tempermonkey安装就没问题
