### ISSUE TITLE
Popup Search 自动复制问题反馈

### ISSUE THREAD

**Issue by smdx** [lkytal/GM#72]
Popup Search 自动复制功能有时会复制淘宝搜索栏的内容，例如搜索了某些物品然后在显示列表中复制了某个名称再到
搜索栏全选原有的搜索栏内容，就会自动复制上搜索栏的内容了。请问是bug还是使用的问题？谢谢

**Comment by lkytal** [comment]
在我的测试中未发现这个情况, 请检查扩展冲突
