### ISSUE TITLE
@homepageURL is broken

### ISSUE THREAD

**Issue by raingart** [lkytal/GM#8]
file: scroll.user.js
is broken (line 9):
@homepageURL				https://lkytal.github.io/coldfire/GM

strange link. What is this blank file? (line 18): 
@updateURL				https://git.oschina.net/coldfire/GM/raw/master/meta/scroll.meta.js
branch **meta**??

**Comment by lkytal** [comment]
Thanks for your feedback about 'homepageurl'. However, the 'updateurl' should not be a blank file.
